[package]
name = "epilogos-workcell-runtime"
version = "0.1.0"
edition.workspace = true

[dependencies]
epilogos-workcell-artifact = { path = "../workcell-artifact" }
epilogos-workcell-core = { path = "../workcell-core" }
epilogos-workcell-workspace = { path = "../workcell-workspace" }

[dev-dependencies]
epilogos-workcell-fabric = { path = "../workcell-fabric" }
